from flasgger import Schema, fields

class CyhyHostScansSchema(Schema):
    accuracy = fields.Int()
    classes = fields.Int()
    hostname = fields.Str()
    ip = fields.Str()
    ip_int = fields.Int()
    latest = fields.Str()
    line = fields.Int()
    owner = fields.Str()
    snapshots = fields.Int()
    source = fields.Str()
    time = fields.Str()

class CyhyOwnersQueryBodySchema(Schema):
    keyword = fields.Str()
    sort_dir = fields.Str()
    limit = fields.Int()
    page = fields.Int()

class CyhyHostQueryBodySchema(Schema):
    time = fields.Str()
    sort_dir = fields.Str()
    limit = fields.Int()
    page = fields.Int()

class CyhyPortScansServiceSchema(Schema):
    conf = fields.Str()
    cpe = fields.Int()
    devicetype = fields.Str()
    extrainfo = fields.Str()
    hostname = fields.Str()
    method = fields.Str()
    name = fields.Str()
    ostype = fields.Str()
    product = fields.Str()
    tunnel = fields.Str()
    version = fields.Str()

class CyhyPortScansSchema(Schema):
    ip = fields.Str()
    ip_int = fields.Int()
    latest = fields.Str()
    owner = fields.Str()
    port = fields.Str()
    protocol = fields.Str()
    reason = fields.Str()
    service = fields.Nested(CyhyPortScansServiceSchema)
    snapshots = fields.Int()
    source = fields.Str()
    state = fields.Str()
    time = fields.Str()

class CyhyPortQueryBodySchema(Schema):
    time = fields.Str()
    sort_dir = fields.Str()
    limit = fields.Int()
    page = fields.Int()

class CyhyTicketsQueryBodySchema(Schema):
    last_change = fields.Str()
    time_closed = fields.Str()
    time_opened = fields.Str()
    sort_dir = fields.Str()
    limit = fields.Int()
    page = fields.Int()

class CyhyTicketsDetailsSchema(Schema):
    cve = fields.Str()
    cvss_base_score = fields.Decimal()
    name = fields.Str()
    score_source = fields.Str()
    severity = fields.Int()

class CyhyTicketsSchema(Schema):
    details = fields.Nested(CyhyTicketsDetailsSchema)
    events = fields.Int()
    false_positive = fields.Bool()
    ip = fields.Str()
    ip_int = fields.Int()
    last_changeloc = fields.Str()
    open = fields.Str()
    owner = fields.Str()
    port = fields.Int()
    protocol = fields.Str()
    snapshots = fields.Int()
    source = fields.Str()
    source_id = fields.Int()
    time_closed = fields.Str()
    time_opened = fields.Str()

class CyhyVulnSchema(Schema):
    agent = fields.Str()
    asset_inventory = fields.Str()
    bid = fields.Str()
    canvas_package = fields.Str()
    cert = fields.Str()
    cert_cc = fields.Str()
    cisco_bug_id = fields.Str()
    cisco_sa = fields.Str()
    cpe = fields.Str()
    cve = fields.Str()
    cvss3_base_score = fields.Decimal()
    cvss3_temporal_score = fields.Decimal()
    cvss3_temporal_vector = fields.Str()
    cvss3_vector = fields.Str()
    cvss_base_score = fields.Decimal()
    cvss_score_rationale = fields.Str()
    cvss_score_source = fields.Str()
    cvss_temporal_score = fields.Decimal()
    cvss_temporal_vector = fields.Str()
    cvss_vector = fields.Str()
    cwe = fields.Str()
    d2_elliot_name = fields.Str()
    description = fields.Str()
    exploit_available = fields.Str()
    exploit_framework_canvas = fields.Str()
    exploit_framework_core = fields.Str()
    exploit_framework_d2_elliot = fields.Str()
    exploit_framework_metasploit = fields.Str()
    exploitability_ease = fields.Str()
    exploited_by_nessus = fields.Str()
    fname = fields.Str()
    iavaiavb = fields.Str()
    in_the_news = fields.Str()
    ip = fields.Str()
    ip_int = fields.Int()
    latest = fields.Bool()
    metasploit_name = fields.Str()
    msft = fields.Str()
    mskb = fields.Str()
    owner = fields.Str()
    patch_publication_date = fields.Str()
    plugin_family = fields.Str()
    plugin_id = fields.Int()
    plugin_modification_date = fields.Str()
    plugin_name = fields.Str()
    plugin_output = fields.Str()
    plugin_publication_date = fields.Str()
    plugin_type = fields.Str()
    port = fields.Int()
    potential_vulnerability = fields.Str()
    protocol = fields.Str()
    risk_factor = fields.Str()
    script_version = fields.Str()
    see_also = fields.Str()
    service = fields.Str()
    severity = fields.Int()
    snapshots = fields.Str()
    solution = fields.Str()
    source = fields.Str()
    stig_severity = fields.Str()
    synopsis = fields.Str()
    time = fields.Str()
    unsupported_by_vendor = fields.Str()
    vuln_publication_date = fields.Str()
    xref = fields.Str()

class CyhyVulnQueryBodySchema(Schema):
    patch_publication_date = fields.Str()
    plugin_publication_date = fields.Str()
    plugin_modification_date = fields.Str()
    vuln_publication_date = fields.Str()
    time = fields.Str()